### ISSUE TITLE
Error in cors

### ISSUE THREAD

**Issue by Daniellop1** [faisalsayed10/firefiles#18]
Hey, I'm getting this error while trying to set cors.

`ArgumentException: JSON CORS data could not be loaded from: [ { "origin": ["https://drive.daniellop.me”], "method": ["GET"], "maxAgeSeconds": 3600 } ]`

**Comment by faisalsayed10** [comment]
Hey, can you please provide what command you are using?

**Comment by Daniellop1** [comment]
I'm using `gsutil cors set cors.json <your-bucket-url>`

**Comment by Daniellop1** [comment]
Says that does not exist

**Comment by faisalsayed10** [comment]
Hmm so you probably messed up the first command maybe?
First you should do this:
```
rm cors.json 
echo "[ { \"origin\": [\"https://drive.daniellop.me\"], \"method\": [\"GET\"], \"maxAgeSeconds\": 3600 } ]" >> cors.json
```

and then run the gsutil command

**Comment by faisalsayed10** [comment]
I think this could be the problem:
![image](https://user-images.githubusercontent.com/36627266/153247740-5ea82712-eaf5-4ba2-b82f-085c86c53d1d.png)
Notice how your closing quotes look a bit different

**Comment by Daniellop1** [comment]
Thanks a lot! now works

**Comment by faisalsayed10** [comment]
You're welcome! do you have any idea what was wrong?

**Comment by Daniellop1** [comment]
I think is because my keyboard
