### ISSUE TITLE
There is a link error.

### ISSUE THREAD

**Issue by pi-dal** [faisalsayed10/firefiles#2]
A great project. But I found that [this link](https://firefiles.vercel.app/docs/intro) does not seem to exist.

**Comment by faisalsayed10** [comment]
Thank you for reporting! Do you want to make a PR or shall I fix it?

**Comment by pi-dal** [comment]
I want to help, but do you want `https://firefiles.vercel.app/docs/intro `or `https://firefiles.vercel.app/docs`? Maybe you will modify this kind of small bug more quickly, so it's up to you, buddy.

**Comment by pi-dal** [comment]
I also found that 'https://usefirefiles.vercel.app/' appears in some places. Should we unify it into `https://firefiles.vercel.app/ `

**Comment by pi-dal** [comment]
If you just want to change the link in the file, I have mentioned pr. Look here #3 .

**Comment by faisalsayed10** [comment]
I've written usefirefiles because the project itself is at that domain but only the landing is at firefiles.vercel.app, other than that everything looks good to me in that pr :)

**Comment by pi-dal** [comment]
I see. I have updated pr.

**Comment by faisalsayed10** [comment]
Cool Thanks!
