### ISSUE TITLE
Add Oracle Block Storage as a provider

### ISSUE THREAD

**Issue by micahlt** [faisalsayed10/firefiles#32]
Oracle offers 200GB of free cloud storage - I'd love to see an integration there!  This definitely wouldn't be a very easy thing to integrate though.

**Comment by faisalsayed10** [comment]
Hello, lets keep this issue open and I'll definitely post a message here when we implement it!

**Comment by micahlt** [comment]
Appreciate this project!  It's a super cool idea, and always great to see fellow young devs taking initiative.

**Comment by faisalsayed10** [comment]
Block storage isn't really a storage meant for storing normal files and folders. So it doesn't seem like it's possible apparently :(
