### ISSUE TITLE
SendGrid now makes it difficult to create a free account

### ISSUE THREAD

**Issue by nexusdiscord** [faisalsayed10/firefiles#36]
maybe can it be replaced with sendinblue.com

**Comment by faisalsayed10** [comment]
Hi @nexusdiscord, what issues are you facing while trying to create a new free account on SendGrid?

**Comment by faisalsayed10** [comment]
Ah have you tried creating a new account? maybe it's something related to your account that they had to flag it for review?

**Comment by faisalsayed10** [comment]
The problem with sendinblue is that the emails sent through it often end up in spam. iirc, we were intially using sendinblue itself
