### ISSUE TITLE
Add Wasabi Integration to the app

### ISSUE THREAD

**Issue by faisalsayed10** [faisalsayed10/firefiles#39]
_For CodeDay Labs_

[Wasabi](https://wasabi.com/) is yet another object storage platform that would be a very good integration to have in our app. The good part is that [Wasabi fully supports the AWS S3 API](https://docs.wasabi.com/docs/wasabi-api), So we don't need to reinvent the wheel again!

If you look into our codebase right now, you'll see that we support Backblaze and AWS both at the same time. Also, we have only written the code for supporting S3, and it works out of the box for Backblaze! (with some minor conditional changes wherever required)
<img width="428" alt="image" src="https://user-images.githubusercontent.com/36627266/236668252-f37287bb-bf11-4620-aa48-33bab192599e.png">

Example: conditions inside `useS3.tsx` wherever small changes are required depending on the bucket:
<img width="827" alt="image" src="https://user-images.githubusercontent.com/36627266/236668311-7f2302ad-39ca-4a0b-8e9b-26cdf79dae6c.png">

Okay, so now, your job is to integrate Wasabi in a similar manner by making the `useS3` hook compatible with it.

- First, create a new file inside `pages/new/` directory which will be used to get the credentials for that provider. (refer other files to get an idea)
- Then, make changes in the `useS3` hook wherever required. Explore how we've integrated Backblaze and try to follow it.
- Navigate to `util/globals.ts` and add an object for your provider to the `PROVIDERS` array. (Also add a logo for the provider in the `public/` directory)
- Navigate to `util/types.ts` and add your provider's name to the `Provider` enum.
- Finally, navigate to the `useBucket` hook and add a case for your provider and return that hook.
- Also make sure to edit any provider-specific functions to make them work with your provider. (look for switch cases or if/else statements that check for the type of provider).

Refer to CONTRIBUTING.md for further guide: https://github.com/faisalsayed10/firefiles/blob/main/docs/CONTRIBUTING.md#testing

**Comment by 9brian** [comment]
working on this

**Comment by faisalsayed10** [comment]
Awesome

**Comment by nghiapham1026** [comment]
Hello Faisal, in the conributing.md file you mention a set of environmental variables needed for the app to run properly. Is deploying those variables necessary for testing the hook of this issue or is it only for exporting the final product?

**Comment by faisalsayed10** [comment]
Yeah, if you'd like to test the app in your development environment, you'd have to set up those envs. 

`cookie password`, `jwt_secret`, and `cipher key` are randomly generated. `SendGrid API key` can be obtained once you set up a free SendGrid account. `email_from` is the email that you would setup in SendGrid through which the emails would be sent (any email is fine for testing, it won't matter—just need it for the login link)

Finally, you'll have to setup a local MySQL database and get its connection URL
