### ISSUE TITLE
Add Digital Ocean integration to the app

### ISSUE THREAD

**Issue by faisalsayed10** [faisalsayed10/firefiles#43]
_For CodeDay Labs_

[Digital Ocean](https://www.digitalocean.com/) is yet another object storage platform that would be a very good integration to have in our app. The good part is that [Digital Ocean fully supports the AWS S3 API](https://docs.digitalocean.com/reference/api/spaces-api/#aws-s3-compatibility), So we don't need to reinvent the wheel again!

If you look into our codebase right now, you'll see that we support Backblaze and AWS both at the same time. Also, we have only written the code for supporting AWS S3, but it works out of the box for Backblaze! (with some minor conditional changes wherever required)
<img width="428" alt="image" src="https://user-images.githubusercontent.com/36627266/236668252-f37287bb-bf11-4620-aa48-33bab192599e.png">

Example: conditions inside `useS3.tsx` wherever small changes are required depending on the bucket:
<img width="827" alt="image" src="https://user-images.githubusercontent.com/36627266/236668311-7f2302ad-39ca-4a0b-8e9b-26cdf79dae6c.png">

Okay, so now, your job is to integrate Digital Ocean in a similar manner by making the `useS3` hook compatible with it.

- First, create a new file inside `pages/new/` directory which will be used to get the credentials for that provider. (refer other files to get an idea)
- Then, make changes in the `useS3` hook wherever required. Explore how we've integrated Backblaze and try to follow it.
- Navigate to `util/globals.ts` and add an object for your provider to the `PROVIDERS` array. (Also add a logo for the provider in the `public/` directory)
- Navigate to `util/types.ts` and add your provider's name to the `Provider` enum.
- Finally, navigate to the `useBucket` hook and add a case for your provider and return that hook.
- Also make sure to edit any provider-specific functions to make them work with your provider. (look for switch cases or if/else statements that check for the type of provider).

Refer to CONTRIBUTING.md for further guide: https://github.com/faisalsayed10/firefiles/blob/main/docs/CONTRIBUTING.md#testing

**Comment by faisalsayed10** [comment]
Similar to #39

**Comment by faisalsayed10** [comment]
Any Digital Ocean costs related to the storage buckets during the development will be reimbursed.

**Comment by sabrinaspage** [comment]
@nghiapham1026 and @9brian are working on this.
