### ISSUE TITLE
Implement file filtering

### ISSUE THREAD

**Issue by faisalsayed10** [faisalsayed10/firefiles#45]
To be picked after #44.

Once tags have been implemented in our app. We need to allow users to filter their files based on the tags they select. Implement filtering within the directories for now.

**BONUS:** If you're looking for a challenge, consider implementing the filter system across the entire storage bucket (i.e. cross-directory) and even a global filtering system that filters files across all the buckets that a user has.

**Comment by Cao1224** [comment]
I am working on this with @alisonfung and @nehapinni.  If there's any advice or suggestions, please let us know. Thank you :)
